//! PR-B adversarial sweep — 44 edge-case fixtures generated by a 3-agent
//! workflow, each with a precise expected runtime result. Aggregates ALL
//! divergences into one report so a single run surfaces every bug.
//!
//! "neg" fixtures end every path in `return 0 - K` and trap; the decoded K is
//! the actual. "run_out" fixtures end in `s.as_output()`; the emitted bytes are
//! the actual.

use sigil_compiler::compile_tool;
use sigil_runtime::ephemeral::ToolError;
use sigil_runtime::execute_ephemeral;
use sigil_runtime::grants::IoGrants;

fn run_neg(body: &str) -> Result<String, String> {
    let src = format!(
        "module tool;\npub fn tool_main(input_ptr: i64, input_len: i64) -> i64 {{\n{body}\n}}\n"
    );
    let result = compile_tool(&src).map_err(|e| format!("COMPILE_ERR: {e:?}"))?;
    match execute_ephemeral(&result.wasm, b"", result.fuel_budget, &IoGrants::none()) {
        Err(ToolError::Trapped { message }) => {
            let p = "tool returned error (";
            match message.find(p) {
                Some(i) => {
                    let s = i + p.len();
                    let e = message[s..].find(')').ok_or("no-close-paren")?;
                    Ok(message[s..s + e].to_string())
                }
                None => Err(format!("TRAP_NO_SENTINEL: {message}")),
            }
        }
        Ok(_) => Err("NO_TRAP (returned non-negative)".to_string()),
        Err(other) => Err(format!("EXEC_ERR: {other:?}")),
    }
}

fn run_out(body: &str) -> Result<String, String> {
    let src = format!(
        "module tool;\npub fn tool_main(input_ptr: i64, input_len: i64) -> i64 ! {{ Alloc }} {{\n{body}\n}}\n"
    );
    let result = compile_tool(&src).map_err(|e| format!("COMPILE_ERR: {e:?}"))?;
    match execute_ephemeral(&result.wasm, b"", result.fuel_budget, &IoGrants::none()) {
        Ok(exec) => String::from_utf8(exec.output).map_err(|e| format!("NON_UTF8: {e}")),
        Err(other) => Err(format!("EXEC_ERR: {other:?}")),
    }
}

/// (kind, body, expected). kind = "neg" | "out".
const FIXTURES: &[(&str, &str, &str)] = &[
    // ---- parse ----
    (
        "neg",
        r#"    let s: str = "007";
    match s.parse_u64() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 999999; },
    }"#,
        "8",
    ),
    (
        "neg",
        r#"    let s: str = "0";
    match s.parse_u64() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 999999; },
    }"#,
        "1",
    ),
    (
        "neg",
        r#"    let s: str = "+5";
    match s.parse_u64() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 999999; },
    }"#,
        "999999",
    ),
    (
        "neg",
        r#"    let s: str = "12x";
    match s.parse_u32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    (
        "neg",
        r#"    let s: str = "4294967295";
    match s.parse_u32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 7; },
    }"#,
        "4294967296",
    ),
    (
        "neg",
        r#"    let s: str = "4294967296";
    match s.parse_u32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    (
        "neg",
        r#"    let s: str = "10000000000";
    match s.parse_u32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    (
        "neg",
        r#"    let s: str = "-1";
    match s.parse_u32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 1); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    (
        "neg",
        r#"    let s: str = "2147483647";
    match s.parse_i32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 3000000000); },
        None => { return 0 - 7; },
    }"#,
        "5147483647",
    ),
    (
        "neg",
        r#"    let s: str = "2147483648";
    match s.parse_i32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 3000000000); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    (
        "neg",
        r#"    let s: str = "-2147483648";
    match s.parse_i32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 3000000000); },
        None => { return 0 - 7; },
    }"#,
        "852516352",
    ),
    (
        "neg",
        r#"    let s: str = "-2147483649";
    match s.parse_i32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 3000000000); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    (
        "neg",
        r#"    let s: str = "-0";
    match s.parse_i32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 3000000000); },
        None => { return 0 - 7; },
    }"#,
        "3000000000",
    ),
    (
        "neg",
        r#"    let s: str = "-";
    match s.parse_i32() {
        Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi + 3000000000); },
        None => { return 0 - 7; },
    }"#,
        "7",
    ),
    // ---- to_string + eq_ignore_case ----
    (
        "out",
        r#"let m: i64 = 0 - 1; let big: u64 = m.as_u64(); let s: str = big.to_string(); return s.as_output();"#,
        "18446744073709551615",
    ),
    // NOTE: 2^63, i64::MIN, and i32::MIN cannot be written as positive int
    // literals (2^63 / 9223372036854775808 overflows i64; `let n: i32 =
    // 0 - 2147483648` hits a PRE-EXISTING narrow-int-literal wasm-codegen bug,
    // task flagged separately). They are constructed here via i64::MAX + as_*
    // so these fixtures still exercise to_string at the true boundary values.
    (
        "out",
        r#"let mx: i64 = 9223372036854775807; let u: u64 = mx.as_u64(); let one: u64 = 1; let big: u64 = u + one; let s: str = big.to_string(); return s.as_output();"#,
        "9223372036854775808",
    ),
    (
        "out",
        r#"let mx: i64 = 9223372036854775807; let n: i64 = (0 - mx) - 1; let s: str = n.to_string(); return s.as_output();"#,
        "-9223372036854775808",
    ),
    (
        "out",
        r#"let big: i64 = 0 - 2147483648; let n: i32 = big.as_i32(); let s: str = n.to_string(); return s.as_output();"#,
        "-2147483648",
    ),
    (
        "out",
        r#"let m: i64 = 4294967295; let u: u32 = m.as_u32(); let s: str = u.to_string(); return s.as_output();"#,
        "4294967295",
    ),
    (
        "out",
        r#"let z: i64 = 0; let u: u64 = z.as_u64(); let s: str = u.to_string(); return s.as_output();"#,
        "0",
    ),
    (
        "out",
        r#"let n: i64 = 1000200; let s: str = n.to_string(); return s.as_output();"#,
        "1000200",
    ),
    (
        "out",
        r#"let z: i32 = 0; let s: str = z.to_string(); return s.as_output();"#,
        "0",
    ),
    (
        "neg",
        r#"let a: str = "Hello"; let b: str = "hELLO"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "1",
    ),
    (
        "neg",
        r#"let a: str = "ABC123"; let b: str = "abc123"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "1",
    ),
    (
        "neg",
        r#"let a: str = "["; let b: str = "{"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "2",
    ),
    (
        "neg",
        r#"let a: str = "@"; let b: str = "`"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "2",
    ),
    (
        "neg",
        r#"let a: str = "Z"; let b: str = "z"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "1",
    ),
    (
        "neg",
        r#"let a: str = "é"; let b: str = "É"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "2",
    ),
    (
        "neg",
        r#"let a: str = ""; let b: str = ""; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "1",
    ),
    (
        "neg",
        r#"let a: str = ""; let b: str = "a"; if a.eq_ignore_case(b) { return 0 - 1; } else { return 0 - 2; }"#,
        "2",
    ),
    // ---- split_first + dispatch ----
    (
        "out",
        r#"let s: str = "=ab"; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = r.len(); return h.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "",
    ),
    (
        "out",
        r#"let s: str = "=ab"; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = h.len(); return r.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "ab",
    ),
    (
        "out",
        r#"let s: str = "ab="; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = r.len(); return h.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "ab",
    ),
    (
        "neg",
        r#"let s: str = "ab="; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let rl: i64 = r.len(); return 0 - (rl + 1); }, None => { return 0 - 9999; }, }"#,
        "1",
    ),
    (
        "out",
        r#"let s: str = "a::b"; let d: str = "::"; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = h.len(); return r.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "b",
    ),
    (
        "out",
        r#"let s: str = "a::b"; let d: str = "::"; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = r.len(); return h.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "a",
    ),
    (
        "neg",
        r#"let s: str = "=="; let d: str = "=="; match s.split_first(d) { Some(p) => { let (h, r) = p; let hl: i64 = h.len(); let rl: i64 = r.len(); let code: i64 = (hl * 10) + rl; return 0 - (code + 1); }, None => { return 0 - 9999; }, }"#,
        "1",
    ),
    (
        "neg",
        r#"let s: str = "abc"; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = h.len(); let _v: i64 = r.len(); return 0 - 1; }, None => { return 0 - 7; }, }"#,
        "7",
    ),
    (
        "out",
        r#"let s: str = "a=b=c"; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = h.len(); return r.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "b=c",
    ),
    (
        "out",
        r#"let s: str = "a=b=c"; let d: str = "="; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = r.len(); return h.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "a",
    ),
    (
        "out",
        r#"let s: str = "abc"; let d: str = ""; match s.split_first(d) { Some(p) => { let (h, r) = p; let _u: i64 = h.len(); return r.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "abc",
    ),
    (
        "out",
        r#"let n: i64 = 0 - 2147483648; let s: str = n.to_string(); match s.parse_i32() { Some(v) => { let vi: i64 = v.as_i64(); let back: str = vi.to_string(); return back.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "-2147483648",
    ),
    (
        "out",
        r#"let m: i64 = 0 - 1; let big: u64 = m.as_u64(); let s: str = big.to_string(); match s.parse_u64() { Some(v) => { let r: str = v.to_string(); return r.as_output(); }, None => { let z: str = "NONE"; return z.as_output(); }, }"#,
        "18446744073709551615",
    ),
    (
        "neg",
        r#"let z0: i64 = 0; let u: u32 = z0.as_u32(); let s0: str = "4294967295"; match s0.parse_u32() { Some(v) => { let vi: i64 = v.as_i64(); return 0 - (vi - 4294967294); }, None => { return 0 - 9999; }, }"#,
        "1",
    ),
];

#[test]
fn pr_b_adversarial_sweep() {
    let mut failures: Vec<String> = Vec::new();
    for (i, (kind, body, expected)) in FIXTURES.iter().enumerate() {
        let actual = match *kind {
            "neg" => run_neg(body),
            "out" => run_out(body),
            other => panic!("bad kind {other}"),
        };
        match actual {
            Ok(got) if got == *expected => {}
            Ok(got) => failures.push(format!(
                "[#{i} {kind}] MISMATCH expected={expected:?} got={got:?}\n  body: {body}"
            )),
            Err(why) => failures.push(format!(
                "[#{i} {kind}] {why}\n  expected={expected:?}\n  body: {body}"
            )),
        }
    }
    if !failures.is_empty() {
        panic!(
            "\n{} of {} adversarial fixtures diverged:\n\n{}\n",
            failures.len(),
            FIXTURES.len(),
            failures.join("\n\n")
        );
    }
}
