pub const SOURCES: &[(&str, &str)] = &[
    ("pipeline", include_str!("../pipeline_differential.rs")),
    ("monomorph", include_str!("../monomorph_differential.rs")),
    ("typecheck", include_str!("../typecheck_differential.rs")),
    ("selfhost", include_str!("../selfhost_self_census.rs")),
    ("runtime", include_str!("../runtime_differential_census.rs")),
    ("lexer", include_str!("../lexer_differential.rs")),
    ("parser", include_str!("../parser_differential.rs")),
    ("claims", include_str!("../claims_ledger.rs")),
    ("soundness", include_str!("../soundness_contract.rs")),
    ("imports", include_str!("../runtime_import_contract.rs")),
    ("taint", include_str!("../taint_check_differential.rs")),
    (
        "capability",
        include_str!("../cap_workload_differential.rs"),
    ),
    ("effect", include_str!("../effect_check_differential.rs")),
    ("ring", include_str!("../ring_check_differential.rs")),
    ("ownership", include_str!("../own_check_differential.rs")),
];

/// Blank-line-separated blocks: `source key|suite name|case floor`, then required test labels.
pub const CASES: &str = r#"
pipeline|pipeline differential|31
boot0_first_fail_order boot0_oracle_deterministic boot0_protocol_comparison
boot0_mega_composition_feasible boot1_pipeline_parity boot1_unsupported_taint_shape_fails_closed
boot1_execution_capstone boot1_every_gate_fires boot1_deterministic mono4_composed_parity
mono4_execution_capstone mono4_deterministic bcompose_composed_parity
bcompose_execution_capstone bcompose_deterministic cap0_oracle_accepts_capstone_input
cap0_poison_census_ratchet boot_self_byte_capstone cap0_runnable_poison_census_zero
boot_self_runnable_byte_capstone stage3a_bare_library_has_no_entry stage3a_executable_closure
stage3b_ddc_honest_passes_backdoored_caught stage3b_backdoor_targets_only_self
stage3b_backdoored_compiler_still_functions ag6_5_with_driver_byte_capstone
pin_certified_artifact_size pin_census_anti_vacuity pin7_digest_instrument_is_not_vacuous
pin_certified_artifact_digest pin_strip_list_length

monomorph|monomorph differential|106
mono0_census_pins mono0_layout_asymmetry mono0_poly_recursion_rejects_loud
mono0_oracle_deterministic mono1_census_parity mono1_non_stub_pins mono1_deterministic
mono2_census_parity mono2_non_stub_pins mono2_layout_parity mono2_deterministic
mono3_code_section_parity mono3_execution_capstone mono3_clone_hygiene mono3_deterministic
mono3b_whole_module_parity mono5_whole_module_parity mono5_census_expansion_conservation
mono5_execution_capstone mono5_deterministic mono6_whole_module_parity mono6_execution_capstone
mono6_deterministic mono6_fence_generic_fn_generic_record_param mono6_fence_mono5_interaction
mono7_whole_module_parity mono7_execution_capstone mono7_deterministic
mono7_fence_method_own_type_param bvec_whole_module_parity bvec_execution_capstone
bvec_deterministic blet_whole_module_parity blet_push_roundtrip_accept blet_fences
bdisp_whole_module_parity bdisp_arena_roundtrip_accept bdisp_deterministic
bassoc_whole_module_parity bassoc_vec_lifecycle_accept bassoc_arena_lifecycle_accept
bassoc_fences bassoc_deterministic wstra_whole_module_parity wstra_execution_accept wstra_fences
wstra_deterministic wstrb_whole_module_parity wstrb_execution_accept wstrb_deterministic
wconst_whole_module_parity wconst_execution_accept wconst_deterministic
wtuple_whole_module_parity wtuple_execution_accept wtuple_deterministic welem_byte_parity
welem_exec_capstone_rec welem_exec_capstone_str welem_narrow_fence welem_deterministic
wmod_byte_parity wmod_exec_capstone wmod_deterministic wsf_byte_parity wsf_exec_capstone
wsf_deterministic wsr_byte_parity wsr_deterministic wfv_byte_parity wfv_exec_capstone
wfv_deterministic wic_byte_parity wic_exec_capstone wic_deterministic wfi_byte_parity
wfi_nonint_fence wfi_deterministic wte_byte_parity wte_fence_path_rhs wte_exec_capstone
wte_deterministic wvb_byte_parity wvb_exec_capstone wvb_deterministic wci_byte_parity
wci_exec_capstone wci_deterministic wcl_byte_parity wcl_exec_capstone wcl_deterministic
wce_byte_parity wce_exec_capstone wce_deterministic wcm_byte_parity wcm_exec_capstone
wcm_deterministic ag6_fail_closed_invariant ag6_multipayload_match_parity ag6_multipayload_exec
ag6_match_no_fail_open ag6_generic_enum_method_corpus ag6_generic_enum_method_no_divergence
pin_fence_registry_never_diverges ag6_6_narrow_variant_size_corpus
ag6_7_unresolved_generic_enum_contexts_fail_closed

typecheck|typecheck differential|110
a8_span_parity_has_teeth pr_c0_cap_decl_is_inert_no_op pr_c1_cap_value_records_match_oracle
pr_c1_cap_deferred_shapes_no_false_code pr_match_field_scrutinee_match_oracle
pr1a_return_expression_types_match_oracle pr1b_binary_operators_match_oracle
pr_e2_if_let_while_let_match_oracle pr_e3a_fstring_match_oracle
pr1c_let_bindings_and_annotations_match_oracle pr2a_variable_references_match_oracle
pr2b_function_parameters_match_oracle pr2c_function_calls_match_oracle
pr2c_adversarial_fixtures_match_oracle pr3a_record_types_match_oracle
pr3b_field_access_match_oracle pr3c_record_construction_match_oracle pr3d_enums_match_oracle
pr4a_control_flow_match_oracle pr4d_enum_payload_match_oracle
pr4d_adversarial_fixtures_match_oracle pr4b_match_match_oracle
pr4c_int_literal_pinning_match_oracle pr1a_is_deterministic
pr2a_adversarial_fixtures_match_oracle pr3b_adversarial_fixtures_match_oracle
pr3c_adversarial_fixtures_match_oracle pr3d_adversarial_fixtures_match_oracle
pr4a_adversarial_fixtures_match_oracle pr4b_adversarial_fixtures_match_oracle
pr4c_adversarial_fixtures_match_oracle pr5a_mismatch_codes_match_oracle
pr5a_wellformed_programs_emit_no_codes pr5a_adversarial_neg_codes_match_oracle
pr5a_adversarial_pos_emit_no_codes pr5b_codes_match_oracle pr5b_wellformed_emit_no_codes
pr5b_adversarial_neg_codes_match_oracle pr5b_adversarial_pos_emit_no_codes
pr5c_codes_match_oracle pr5c_wellformed_emit_no_codes pr5c_adversarial_neg_codes_match_oracle
pr5c_adversarial_pos_emit_no_codes pr5d_codes_match_oracle pr5d_wellformed_emit_no_codes
pr5d_adversarial_neg_codes_match_oracle pr5d_adversarial_pos_emit_no_codes
pr5e_composite_types_match_oracle pr5e_type_detail_known_answers pr5e_mangle_injective
pr5e_adversarial_pos_match_oracle pr5e_adversarial_neg_codes_match_oracle
pr5f_composite_literals_match_oracle pr5f_adversarial_pos_match_oracle
pr5f_adversarial_neg_codes_match_oracle pr5g_block_scope_resolution_match_oracle
pr5g_adversarial_pos_match_oracle pr5g_adversarial_neg_codes_match_oracle
pr5h_corpus_coverage_min_covered pr5h_no_intlit_no_error_in_clean_stream
pr5h_real_sigil_fixtures_match_oracle pr5h_reject_for_the_right_reason_roundtrip
pr5i_composite_value_checks pr5i_adversarial_pos_match_oracle
pr5i_adversarial_neg_codes_match_oracle pr5j_composite_call_and_refparam
pr5j_adversarial_pos_match_oracle pr5j_adversarial_neg_codes_match_oracle pr6a_decl_coherence
pr6a_adversarial_pos_match_oracle pr6a_adversarial_neg_codes_match_oracle
pr6b_bound_satisfaction pr6b_adversarial_pos_emit_no_codes
pr6b_adversarial_neg_codes_match_oracle pr_g0_generic_recognition
pr_g0_instance_filter_is_noop_on_monomorphic pr_g0_zero_generic_tag_in_stream
pr_g1a_concrete_arg_binding_records pr_g1a_uninferrable_return_type_param_fires_t150
pr_g1a_adversarial_pos_match_oracle pr_g1a_adversarial_neg_codes_match_oracle
pr_g2a_generic_record_field_substitution pr_g2a_substituted_field_participates_in_checks
pr_g2a_adversarial_pos_match_oracle pr_g2a_adversarial_neg_codes_match_oracle
pr_g2a_ii_unannotated_record_inference pr_g2a_ii_t233_and_inferred_read_codes
pr_g2a_ii_adversarial_pos_match_oracle pr_g2a_ii_adversarial_neg_codes_match_oracle
pr_g2a_iii_construct_field_t071_and_t234 pr_g2a_iii_adversarial_pos_match_oracle
pr_g2a_iii_adversarial_neg_codes_match_oracle pr_g3a_nongeneric_method_calls
pr_g3a_adversarial_pos_match_oracle pr_g3a_adversarial_neg_codes_match_oracle
pr_g3b_generic_impl_methods_match_oracle pr_g3b_adversarial_pos_match_oracle
pr_g3b_adversarial_neg_codes_match_oracle pr_g4_zero_generic_tag_full_corpus
pr_g4_body_code_asymmetry_admission pr_g4_done_line_corpus_parity
pr_g4_nested_generics_match_oracle pr_g4_generic_let_value_check_match_oracle
pr_g4_generic_let_value_check_clean pr_g2b_i_generic_named_return_records_match_oracle
pr_g2b_i_callresult_value_flow_no_false_positive
pr_g2b_ii_match_payload_substitution_match_oracle
pr_g2b_iii_enum_construct_payload_t041_match_oracle
pr_g2b_iii_t236_ambiguous_bare_variant_match_oracle pr_e1_optional_else_match_oracle

selfhost|self-host lane census|18
census_dispatch_canary census_rig_canary self1_stdlib_generic_let_accepted
self2_tc_t060_gap_closed census_row_lexer census_row_parser census_row_name_resolution
census_row_typecheck census_row_ring_check census_row_effect_check census_row_taint_check
census_row_cap_check census_row_own_check census_row_pipeline census_row_air census_row_composed
census_row_composed_default_sandbox_fence census_deterministic_sample

runtime|runtime differential census|4
rtc_import_set_is_fenced rtc_runtime_differential_census rtc_forge_traps_actor_and_cap_ops
rtc_actor_ops_reject_hostile_args

lexer|lexer differential|12
as_output_round_trips_a_literal as_output_round_trips_a_constructed_string
as_output_round_trips_input_via_from_bytes lexer_compiles_and_counts_tokens
lexer_empty_source_is_just_eof differential_core_tokens differential_stdlib_corpus
differential_lexer_errors et1_corpus_covers_every_emitted_tag et4_spans_tile_the_source
et8_lex_is_deterministic et7_never_traps_on_adversarial_bytes

parser|parser differential|12
differential_multi_module_program differential_minimal_corpus
differential_caps_typestate_hkt_adversarial differential_effect_handlers
differential_stdlib_corpus et_p6_spans_nest_within_parents et_p8_parse_is_deterministic
et_p1_corpus_covers_every_kind differential_parser_errors et_p8_never_traps_on_adversarial_input
et_p4_no_orphan_nodes_on_clean_corpus et_p9_kind_tags_are_unique

claims|claims ledger|5
pin6_extractors_are_not_vacuous pin6_claim_numbers_are_unique_and_sequential
pin6_every_claim_names_a_real_test pin6_unproven_claim_count_is_pinned
pin6_ledger_numbers_match_the_code

soundness|soundness contract|9
soundness_matrix_rows_are_complete soundness_matrix_test_tags_name_real_tests
residual_risk_rows_are_actionable_and_referenced residual_risk_completion_gate_is_satisfied
security_boundary_decisions_are_explicit public_docs_do_not_restore_known_overclaims
lean_axiom_gate_covers_every_declared_theorem diagnostic_security_surface_is_censused
compiler_security_pipeline_is_complete_and_ordered

imports|runtime import contract|2
host_import_manifests_are_total_over_linker_registrations
declared_host_imports_really_link_and_unknown_imports_fail_closed

taint|taint differential|8
sh_taint_reject_matches_oracle sh_taint_accept_is_clean_both_sides
sh_taint_no_false_tcode_subset sh_taint_non_stub_all_13_fire sh_taint_ag_t14_subset_safe
sh_taint_unsupported_shapes_are_explicit sh_taint_deterministic
sh_taint_stdlib_clean_parity_and_floor

capability|capability workload differential|12
cap0_workload_pins cap_sink_contract_is_deliberately_full_mask
cap0_linearity_makes_trace_flow_free cap0_workload_deterministic cap1_required_parity
cap2_workload_parity cap1_non_stub cap1_shadow_deterministic cap3_verdict_parity
cap3_reject_matches_oracle cap3_accept_clean_both_sides cap3_verdict_non_stub

effect|effect differential|6
sh_effect_reject_matches_oracle sh_effect_accept_is_clean_both_sides
sh_effect_no_false_ecode_subset sh_effect_non_stub sh_effect_deterministic
sh_effect_stdlib_clean_parity_and_floor

ring|ring differential|5
sh_ring_reject_matches_oracle sh_ring_accept_is_clean_both_sides sh_ring_no_false_rcode_subset
sh_ring_non_stub sh_ring_deterministic

ownership|ownership differential|8
own0_oracle_pins own0_cfg_move_state_is_propagated own0_cfg_borrow_state_is_propagated
own0_oracle_deterministic malformed_air_cfg_fails_closed_without_panicking own_verdict_parity
own1_non_stub own1_shadow_deterministic
"#;
